### ISSUE TITLE
Is this project inspired by next.js?

### ISSUE THREAD

**Issue by frol** [threepointone/rakt#5]
Have you heard of Next.js? Could you compare rakt to it, please?

**Comment by threepointone** [comment]
yup, rakt is clearly inspired by the dx from next (and as a historical note, next v1's default css solution was [glamor](https://github.com/threepointone/glamor), one of my projects :) ) What I've 'copied' - focusing on minimal api surface, and owning the compilation/server components. It diverges from next in some key ways - 
- `<Route/>`s can be declared anywhere in your app 
- colocating actual server code with your components 

there are more feature ideas, and a bunch of internal details, that I'll go into detail in the future.
